### ISSUE TITLE
fock你的项目到AppVeyor 里面进行打包成window项目。报错

### ISSUE THREAD

**Issue by lebornjose** [weixin/WeFlow#63]
#### 关于 Issues 的提交说明
请附注以下信息，这将有助于你的 Issues 被更好、更及时的回复和处理：  
建议补充 `报错代码` 或者 `问题截图`，同时，请确保你运行的是 **最新发布的版本**，因为问题可能已经修复。

__ 以上文本阅读后请删除 __

#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.x.x)` 
- [x] WeFlow 版本： `v1.3.2`

#### 反馈具体描述：只接fock你的项目，到AppVeror中进行打包，打包到4min 的时候，出现错误
      rename success.
      crypto.js:87
     this._handle.init(hmac, toBuf(key));
               ^
     TypeError: Not a buffer
        at TypeError (native)
      at new Hmac (crypto.js:87:16)
      at Object.Hmac (crypto.js:85:12)
      at Object.exports.hmacSha1 (C:\projects\weflow\node_modules\qiniu\qiniu\util.js:25:21)
      at PutPolicy.token (C:\projects\weflow\node_modules\qiniu\qiniu\rs.js:218:22)
      at C:\projects\weflow\build\upload.js:39:73
      at C:\projects\weflow\node_modules\async\dist\async.js:3671:13
      at replenish (C:\projects\weflow\node_modules\async\dist\async.js:884:21)
      at iterateeCallback (C:\projects\weflow\node_modules\async\dist\async.js:869:21)
      at C:\projects\weflow\node_modules\async\dist\async.js:847:20
     Command exited with code 1

**Comment by littledu** [comment]
因为你没有我空间的token，上传不上去，你要改一下，回头我写篇文章分享一下
